"""initial schema

Revision ID: c1ca7834ee2b
Revises: 
Create Date: 2026-05-14 10:42:16.675037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1ca7834ee2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'ts')
    )
    op.create_index('ix_candles_symbol_ts_desc', 'candles', ['symbol', 'ts'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candles_symbol_ts_desc', table_name='candles', postgresql_using='btree')
    op.drop_table('candles')
    # ### end Alembic commands ###
